language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-opengl xvfb
install:
  - pip install -r requirements.txt
script:
  - xvfb-run -s "-screen 0 1920x1080x24" pytest --cov=./simulation/
after_success:
  - codecov